import { Movie, MovieChallenge } from "./types";

export const AVAILABLE_EMOJIS = [
  { char: "🍿", label: "Блокбастер" },
  { char: "😱", label: "Жахи / Напруга" },
  { char: "🧠", label: "Інтелектуальне / Пазл" },
  { char: "😭", label: "Сльози / Драма" },
  { char: "😂", label: "Сміх / Комедія" },
  { char: "🤠", label: "Пригоди / Екшн" },
  { char: "🪄", label: "Фентезі / Магія" },
  { char: "❤️", label: "Романтика" },
  { char: "🧬", label: "Наукова фантастика" },
];

export const INITIAL_MOVIES: Movie[] = [
  // --- Modern Ukrainian Masterpieces ---
  {
    id: "ua-luxembourg",
    title: "Люксембург, Люксембург",
    originalTitle: "Luxembourg, Luxembourg",
    year: 2022,
    genres: ["Комедія", "Драма"],
    duration: 110,
    rating: 7.9,
    description: "Коли брати-близнюки дізнаються, що їхній давно зниклий батько захворів у Люксембурзі, вони вирушають у подорож, аби побачити його востаннє — але кожен має свої мотиви.",
    tags: ["Українське кіно", "Сім'я", "Подорож", "Гумор", "Трагікомедія"],
    emojis: ["😂", "😭", "🍿"],
    streaming: ["Netflix", "Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-pamfir",
    title: "Памфір",
    originalTitle: "Pamfir",
    year: 2022,
    genres: ["Драма", "Кримінал", "Трилер"],
    duration: 106,
    rating: 7.8,
    description: "Памфір повертається додому із заробітків у західну Україну напередодні традиційного карнавалу Маланки, але через помилку свого сина змушений відновити зв'язок зі своїм кримінальним минулим.",
    tags: ["Карпати", "Кримінал", "Драма", "Маланка", "Авторське"],
    emojis: ["😱", "😭", "🧠"],
    streaming: ["Netflix", "Sweet.tv"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-mavka",
    title: "Мавка. Лісова пісня",
    originalTitle: "Mavka: The Forest Song",
    year: 2023,
    genres: ["Анімація", "Фентезі", "Пригоди"],
    duration: 99,
    rating: 7.3,
    description: "Мавка, прекрасна Німфа і Душа Лісу, закохується у людину — талановитого музику Лукаша. Вони стикаються з неможливим вибором між коханням і своїм обов'язком.",
    tags: ["Міфологія", "Для всієї родини", "Красивий візуал", "Музика"],
    emojis: ["🍿", "🪄", "❤️"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-my-thoughts-silent",
    title: "Мої думки тихі",
    originalTitle: "My Thoughts Are Silent",
    year: 2019,
    genres: ["Комедія", "Драма"],
    duration: 104,
    rating: 8.1,
    description: "Молодий звукорежисер Вадим отримує замовлення записати голоси рідкісних закарпатських птахів. Якщо йому вдасться, він зможе виїхати до Канади. Але його компаньйоном у поїздці стає мама.",
    tags: ["Іронія", "Стосунки з мамою", "Закарпаття", "Культовий гумор"],
    emojis: ["😂", "😭", "🧠"],
    streaming: ["Sweet.tv", "Megogo", "Netflix"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-dovbush",
    title: "Довбуш",
    originalTitle: "Dovbush",
    year: 2023,
    genres: ["Екшн", "Пригоди", "Історія"],
    duration: 124,
    rating: 7.7,
    description: "Історія про Олексу Довбуша, ватажка опришків, який очолює визвольний рух у Карпатах XVIII століття заради свободи своєї землі та коханої Марічки.",
    tags: ["Історичний епос", "Карпати", "Борці за свободу", "Бойовик"],
    emojis: ["🍿", "🤠", "😭"],
    streaming: ["Netflix", "Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-klondaika",
    title: "Клондайк",
    originalTitle: "Klondike",
    year: 2022,
    genres: ["Драма", "Військовий"],
    duration: 100,
    rating: 7.2,
    description: "2014 рік. Родина живе на кордоні України та Донбасу, коли падає цивільний літак MH17. Попри військові загрози, вагітна Ірина відмовляється евакуюватися зі зруйнованої хати.",
    tags: ["Військова драма", "Авторське кіно", "Трагедія", "Сильна жінка"],
    emojis: ["😭", "😱", "🧠"],
    streaming: ["Sweet.tv"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: ["violence", "tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?w=500&auto=format&fit=crop&q=80"
  },

  // --- International Masterpieces ---
  {
    id: "intl-interstellar",
    title: "Інтерстеллар",
    originalTitle: "Interstellar",
    year: 2014,
    genres: ["Наукова фантастика", "Драма", "Пригоди"],
    duration: 169,
    rating: 8.7,
    description: "Група дослідників вирушає в космічну експедицію через нещодавно виявлену червоточину, щоб знайти новий дім на інших планетах у часи, коли Земля помирає.",
    tags: ["Космос", "Час", "Крістофер Нолан", "Гравітація", "Епічний саундтрек"],
    emojis: ["🧬", "🧠", "😭"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-inception",
    title: "Початок",
    originalTitle: "Inception",
    year: 2010,
    genres: ["Екшн", "Наукова фантастика", "Трилер"],
    duration: 148,
    rating: 8.8,
    description: "Професійний шпигун, що краде корпоративні таємниці через технологію проникнення в сни, отримує зворотне завдання — вкорінити ідею в розум спадкоємця імперії.",
    tags: ["Сни у снах", "Пазл", "Крістофер Нолан", "Екшн", "Дивовижні ефекти"],
    emojis: ["🧠", "🧬", "🍿"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-spirited-away",
    title: "Віднесені привидами",
    originalTitle: "Sen to Chihiro no Kamikakushi",
    year: 2001,
    genres: ["Анімація", "Фентезі", "Сімейний"],
    duration: 125,
    rating: 8.6,
    description: "10-річна дівчинка Чіхіро блукає у чарівному таємничому містечку духів. Після того, як її батьків перетворюють на свиней, вона має знайти роботу та звільнити свою сім'ю.",
    tags: ["Хаяо Міядзакі", "Аніме", "Чарівний світ", "Культова класика"],
    emojis: ["🪄", "❤️", "🍿"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-grand-budapest",
    title: "Готель «Гранд Будапешт»",
    originalTitle: "The Grand Budapest Hotel",
    year: 2014,
    genres: ["Комедія", "Драма", "Пригоди"],
    duration: 100,
    rating: 8.1,
    description: "Пригоди легендарного консьєржа Густава та його юного друга Зеро у вигаданій європейській республіці під час світової війни, пов'язані з крадіжкою безцінної картини.",
    tags: ["Уес Андерсон", "Прекрасна симетрія", "Яскраві кольори", "Гумор", "Детектив"],
    emojis: ["😂", "🍿", "🧠"],
    streaming: ["Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-hachiko",
    title: "Хатіко: Вірний друг",
    originalTitle: "Hachi: A Dog's Tale",
    year: 2009,
    genres: ["Драма", "Сімейний"],
    duration: 93,
    rating: 8.1,
    description: "Неймовірна історія про нескінченну відданість собаки породи Акіта на ім'я Хатіко, який продовжував чекати на залізничній станції свого померлого господаря протягом 9 років.",
    tags: ["Собака", "Сльози", "Сім'я", "Реальні події"],
    emojis: ["😭", "❤️"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["tragic-ending", "animal-death"],
    posterUrl: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-fight-club",
    title: "Бійцівський клуб",
    originalTitle: "Fight Club",
    year: 1999,
    genres: ["Драма", "Трилер"],
    duration: 139,
    rating: 8.8,
    description: "Офісний працівник, що страждає на безсоння, і дивний виробник мила Тайлер Дерден створюють підпільний бійцівський клуб, що переростає у масштабний радикальний анархістський рух.",
    tags: ["Культ", "Психологія", "Бійки", "Неочікуваний фінал"],
    emojis: ["🧠", "😱", "🍿"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1585647347483-22b66260dfff?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-la-la-land",
    title: "Ла-Ла Ленд",
    originalTitle: "La La Land",
    year: 2016,
    genres: ["Драма", "Романтика", "Мюзикл"],
    duration: 128,
    rating: 8.0,
    description: "Джазовий піаніст та молода акторка, що марять про кар'єру в Лос-Анджелесі, закохуються одне в одного. Проте, коли до них приходить успіх, їхні мрії загрожують коханню.",
    tags: ["Мюзикл", "Кохання", "Райдужні сукні", "Голлівуд", "Меланхолія"],
    emojis: ["❤️", "😭", "😂"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-coherence",
    title: "Зв'язок",
    originalTitle: "Coherence",
    year: 2013,
    genres: ["Трилер", "Наукова фантастика"],
    duration: 89,
    rating: 7.2,
    description: "Коли над Землею пролітає рідкісна комета, вісім друзів на званій вечері стикаються з ланцюжком дивних подій, що руйнують простір, час та їхнє відчуття реальності.",
    tags: ["Геніальний мікродетектив", "Квантова фізика", "Паралельні світи", "Камерний"],
    emojis: ["🧠", "😱", "🧬"],
    streaming: ["Apple TV"],
    hasUkDub: false,
    isUkrainian: false,
    isHiddenGem: true,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-perfect-blue",
    title: "Ідеальний смуток",
    originalTitle: "Perfect Blue",
    year: 1997,
    genres: ["Аніме", "Психологічний трилер"],
    duration: 81,
    rating: 8.0,
    description: "Співачка поп-ідол залишає гурт заради акторської кар'єри, але стає жертвою нав'язливого перслідувача та втрачає грань між власним реальним життям, грою та фантазією.",
    tags: ["Психологічне безумство", "Шокуючий трилер", "Аніме", "Шедевр Сатоші Кона"],
    emojis: ["😱", "🧠"],
    streaming: ["Netflix"],
    hasUkDub: false,
    isUkrainian: false,
    isHiddenGem: true,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-knives-out",
    title: "Ножі наголо",
    originalTitle: "Knives Out",
    year: 2019,
    genres: ["Детектив", "Комедія", "Драма"],
    duration: 130,
    rating: 7.9,
    description: "Коли заможний письменник романів жахів помирає за загадкових обставин, ексцентричний детектив Бенуа Блан береться розчистити павутину брехні великої та хижої родини.",
    tags: ["Сучасний детектив", "Сімейні сварки", "Даніель Крейг", "Хитрий сюжет"],
    emojis: ["😂", "🧠", "🍿"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=500&auto=format&fit=crop&q=80"
  },
  // --- Modern & Classic Ukrainian Masterpieces & Series ---
  {
    id: "ua-spijmaty-kajdasha",
    title: "Спіймати Кайдаша",
    originalTitle: "To Catch a Kaidash",
    year: 2020,
    genres: ["Комедія", "Драма", "Серіал"],
    duration: 50,
    rating: 8.6,
    description: "Сучасна інтерпретація класичної повісті Івана Нечуя-Левицького про родину Кайдашів. Вічна сварка батьків та дітей, кохання, побутові драми та неймовірний закарпатський та централноукраїнський колорит.",
    tags: ["Українські серіали", "Сім'я", "Трагікомедія", "Село", "Культовий гумор"],
    emojis: ["😂", "😭", "❤️"],
    streaming: ["Netflix", "Megogo", "Sweet.tv"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1593113598332-cd288d649433?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-first-days",
    title: "Перші дні",
    originalTitle: "Those Who Stayed",
    year: 2023,
    genres: ["Драма", "Серіал"],
    duration: 45,
    rating: 8.0,
    description: "Унікальна антологія з 6 історій від різних українських режисерів про перші тижні після початку повномасштабного вторгнення Росії в лютому 2022 року у Києві. Історії про людяність, страх та любов.",
    tags: ["Українські серіали", "Військова драма", "Сучасність", "Емоційне"],
    emojis: ["😭", "😱", "❤️"],
    streaming: ["Netflix", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-chernobyl",
    title: "Чорнобиль",
    originalTitle: "Chernobyl",
    year: 2019,
    genres: ["Драма", "Трилер", "Серіал"],
    duration: 60,
    rating: 9.4,
    description: "Детальна та надзвичайно напружена реконструкція катастрофи на Чорнобильській АЕС у 1986 році, що розповідає про небезпек безвідповідальної брехні та героїзм звичайних ліквідаторів.",
    tags: ["Чорнобиль", "Катастрофа", "Історія України", "СРСР", "Правда"],
    emojis: ["😱", "😭", "🧠"],
    streaming: ["Megogo", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1517089596392-db9a5e062b1c?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-tini-zabutykh-predkiv",
    title: "Тіні забутих предків",
    originalTitle: "Shadows of Forgotten Ancestors",
    year: 1965,
    genres: ["Драма", "Романтика"],
    duration: 97,
    rating: 7.9,
    description: "Шедевр українського поетичного кіно від Сергія Параджанова. Трагічна історія кохання Івана та Марічки з ворогуючих карпатських родів гуцулів.",
    tags: ["Карпати", "Класика", "Гуцули", "Поетичне кіно", "Сергій Параджанов"],
    emojis: ["❤️", "😭", "🪄"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: ["tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-i-budut-lyudy",
    title: "І будуть люди",
    originalTitle: "There Will Be Humans",
    year: 2020,
    genres: ["Драма", "Серіал"],
    duration: 55,
    rating: 8.2,
    description: "Масштабна історична драма про життя українців на Полтавщині на початку ХХ століття. Пронизливі людські долі у часи Першої світової війни, революції та приходу радянської влади.",
    tags: ["Українські серіали", "Історична сага", "Початок XX століття", "Боротьба"],
    emojis: ["😭", "🧠", "❤️"],
    streaming: ["Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1505673542670-a5e3ff5b14a3?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-kiborgy",
    title: "Кіборги. Герої не вмирають",
    originalTitle: "Cyborgs: Heroes Never Die",
    year: 2017,
    genres: ["Екшн", "Драма"],
    duration: 112,
    rating: 7.8,
    description: "Історія про кількох військових добровольців різного віку та походження, які у вересні 2014 року прибувають захищати Донецький аеропорт під час наступу проросійських сил.",
    tags: ["Військове кіно", "Донецький аеропорт", "Героїзм", "Сучасна війна"],
    emojis: ["🍿", "🤠", "😭"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1508615070457-7baeba4003ab?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-kozaky",
    title: "Козаки. Абсолютно брехлива історія",
    originalTitle: "Cossacks. An Absolutely Untrue Story",
    year: 2020,
    genres: ["Комедія", "Пригоди", "Серіал"],
    duration: 48,
    rating: 8.1,
    description: "Пригодницький екшн-серіал про козаків кінця XVI століття. Селянин Іван викрадає магічну сережку в московського царя, щоб викупити матір з турецького полону, але коштовність потрапляє на Запорозьку Січ.",
    tags: ["Українські серіали", "Козацтво", "Пригоди", "Гумор", "Містика"],
    emojis: ["😂", "🤠", "🪄"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1549417229-aa67d3263c09?w=500&auto=format&fit=crop&q=80"
  },
  // --- International Legendary TV Shows ---
  {
    id: "intl-breaking-bad",
    title: "Пуститися берега",
    originalTitle: "Breaking Bad",
    year: 2008,
    genres: ["Драма", "Трилер", "Серіал"],
    duration: 49,
    rating: 9.5,
    description: "Скромний шкільний вчитель хімії Волтер Вайт дізнається, що хворий на рак легенів. Щоби підтримати фінансове майбутнє своєї сім'ї перед смертю, він починає варити високоякісний метамфетамін разом із колишнім учнем.",
    tags: ["Кримінал", "Альбукерке", "Волтер Вайт", "Наркокартель", "Культова класика"],
    emojis: ["🧠", "😱", "😭"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1551244072-5d12893278ab?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-stranger-things",
    title: "Дивні дива",
    originalTitle: "Stranger Things",
    year: 2016,
    genres: ["Фентезі", "Наукова фантастика", "Серіал", "Пригоди"],
    duration: 55,
    rating: 8.7,
    description: "У маленькому містечку Хоукінс зникає хлопчик. У ході пошуків його друзі стикаються із загадковою дівчинкою з психокінетичними здібностями та відкривають таємний урядовий портал у паралельний моторошний вимір.",
    tags: ["80-ті", "Монстри", "Підлітки", "Потойбіччя", "Ретро-атмосфера"],
    emojis: ["🍿", "🪄", "🧬"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-the-last-of-us",
    title: "Останні з нас",
    originalTitle: "The Last of Us",
    year: 2023,
    genres: ["Екшн", "Драма", "Серіал", "Пригоди"],
    duration: 60,
    rating: 8.8,
    description: "Через двадцять років після того, як сучасна цивілізація була знищена пандемією грибка, загартований уцілілий Джоел наймається, щоб таємно вивести 14-річну Еллі з карантинної зони.",
    tags: ["Апокаліпсис", "Зомбі", "Батьківство", "Емоційне", "Екранізація гри"],
    emojis: ["🍿", "🤠", "😭"],
    streaming: ["Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1621508654686-809f23efdabc?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-wednesday",
    title: "Венздей",
    originalTitle: "Wednesday",
    year: 2022,
    genres: ["Фентезі", "Детектив", "Комедія", "Серіал"],
    duration: 45,
    rating: 8.1,
    description: "Розумна, саркастична та трохи мертва всередині Венздей Аддамс розслідує серію вбивств у новій академії 'Невермор', знаходячи як вірних друзів, так і підступних ворогів.",
    tags: ["Сімейка Аддамс", "Готичне", "Школа Невермор", "Монстри", "Танцювальний вірус"],
    emojis: ["😂", "🧠", "🪄"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-game-of-thrones",
    title: "Гра престолів",
    originalTitle: "Game of Thrones",
    year: 2011,
    genres: ["Фентезі", "Драма", "Серіал", "Пригоди"],
    duration: 60,
    rating: 9.2,
    description: "Дев'ять шляхетних родин ведуть жорстоку війну за контроль над Залізним троном Вестеросу, в той час як стародавній крижаний ворог збирає сили за Стіною на півночі.",
    tags: ["Епічне фентезі", "Дракони", "Королівства", "Інтриги", "Зрада"],
    emojis: ["🍿", "🪄", "😭"],
    streaming: ["Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-rick-and-morty",
    title: "Рік та Морті",
    originalTitle: "Rick and Morty",
    year: 2013,
    genres: ["Анімація", "Наукова фантастика", "Комедія", "Серіал"],
    duration: 22,
    rating: 9.1,
    description: "Неймовірні, божевільні та сповнені чорного гумору космічні пригоди цинічного геніального вченого-алкоголіка Ріка Санчеза та його невпевненого в собі онука Морті.",
    tags: ["Божевільний вчений", "Паралельні всесвіти", "Чорний гумор", "Мультсеріал"],
    emojis: ["😂", "🧬", "🧠"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1601987177651-8edfe6c20009?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-sherlock",
    title: "Шерлок",
    originalTitle: "Sherlock",
    year: 2010,
    genres: ["Детектив", "Драма", "Серіал", "Трилер"],
    duration: 90,
    rating: 9.1,
    description: "Сучасна інтерпретація неперевершених детективів Артура Конан Дойля. Шерлок Холмс та доктор Джон Ватсон розгадують найхитромудріші таємничі вбивства у сучасному Лондоні.",
    tags: ["Лондон", "Бенедикт Камбербетч", "Геніальний розум", "Ватсон"],
    emojis: ["🧠", "😱", "🍿"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-severance",
    title: "Розрив",
    originalTitle: "Severance",
    year: 2022,
    genres: ["Трилер", "Наукова фантастика", "Серіал", "Драма"],
    duration: 50,
    rating: 8.7,
    description: "Корпорація Lumon Industries вводить хірургічний розподіл пам'яті між робочою версією працівника та позаробочою особистістю. Коли один із них починає пошук відповідей, все перетворюється на сюрреалістичну небезпеку.",
    tags: ["Офісна таємниця", "Загадка", "Поділений розум", "Антиутопія"],
    emojis: ["🧠", "😱", "🧬"],
    streaming: ["Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: true,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=500&auto=format&fit=crop&q=80"
  },
  // --- Blockbuster International Movies ---
  {
    id: "intl-dune-2",
    title: "Дюна: Частина друга",
    originalTitle: "Dune: Part Two",
    year: 2024,
    genres: ["Наукова фантастика", "Пригоди", "Екшн"],
    duration: 166,
    rating: 8.6,
    description: "Пол Атрід об'єднується з Чані та фременами, прагнучи помститися змовникам, які знищили його родину. Перед ним стає вибір між коханням та долею всесвіту.",
    tags: ["Космос", "Піщаний хробак", "Дені Вільньов", "Епічний екшн", "Месія"],
    emojis: ["🍿", "🧬", "🤠"],
    streaming: ["Apple TV", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1547483238-f400e65ccd56?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-oppenheimer",
    title: "Оппенгеймер",
    originalTitle: "Oppenheimer",
    year: 2023,
    genres: ["Драма", "Трилер"],
    duration: 180,
    rating: 8.4,
    description: "Історія життя американського фізика Роберта Оппенгеймера, який очолив секретний Мангеттенський проєкт для розробки першої у світі атомної бомби, що навіки змінила людство.",
    tags: ["Атомна бомба", "Крістофер Нолан", "Друга Світова", "Біографія", "Ядерна загроза"],
    emojis: ["🧠", "😱", "🍿"],
    streaming: ["Apple TV", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-dark-knight",
    title: "Темний лицар",
    originalTitle: "The Dark Knight",
    year: 2008,
    genres: ["Екшн", "Трилер", "Драма"],
    duration: 152,
    rating: 9.0,
    description: "За допомогою лейтенанта Джима Гордона та прокурора Гарві Дента Бетмен бореться з організованою злочинністю в Готемі, коли шалений кримінальний розум, відомий як Джокер, кидає місто в анархію.",
    tags: ["Бетмен", "Джокер", "Готем", "Крістофер Нолан", "Бойовик", "Культ"],
    emojis: ["🍿", "🤠", "😱"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-parasite",
    title: "Паразити",
    originalTitle: "Parasite",
    year: 2019,
    genres: ["Трилер", "Драма", "Комедія"],
    duration: 132,
    rating: 8.5,
    description: "Хитра бідна родина вигадує спосіб влаштуватися на роботу до надзвичайно заможної родини Пак, прикидаючись висококласними фахівцями. Проте їхній блискучий паразитичний спосіб життя стикається з несподіваною таємницею.",
    tags: ["Корея", "Хитрий план", "Бідність", "Багатство", "Шокуючий сюжет", "Оскар"],
    emojis: ["🧠", "😱", "😂"],
    streaming: ["Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-whiplash",
    title: "Одержимість",
    originalTitle: "Whiplash",
    year: 2014,
    genres: ["Драма", "Пригоди"],
    duration: 106,
    rating: 8.5,
    description: "Перспективний молодий джазовий барабанщик вступає до елітної консерваторії, де потрапляє під керівництво безкомпромісного, жорстокого диригента-садиста, що не цурається будь-яких методів для виходу за межі можливостей.",
    tags: ["Музика", "Барабани", "Учитель тиран", "Перфекціонізм"],
    emojis: ["🧠", "😭", "🍿"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-the-matrix",
    title: "Матриця",
    originalTitle: "The Matrix",
    year: 1999,
    genres: ["Наукова фантастика", "Екшн"],
    duration: 136,
    rating: 8.7,
    description: "Комп'ютерний хакер Нео дізнається від таємничих повстанців про справжню природу його реальності та його роль у війні проти її контролерів. Культова філософська фантастика.",
    tags: ["Кіберпанк", "Нео", "Повстання машин", "Червона пігулка", "Культовий екшн"],
    emojis: ["🧬", "🧠", "🍿"],
    streaming: ["Netflix", "Apple TV", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-money-heist",
    title: "Паперовий будинок",
    originalTitle: "La Casa de Papel",
    year: 2017,
    genres: ["Трилер", "Екшн", "Серіал", "Драма"],
    duration: 50,
    rating: 8.2,
    description: "Незвичайна група грабіжників намагається здійснити найідеальніше пограбування в історії Іспанії — вкрасти 2,4 мільярда євро з Королівського монетного двору під керівництвом загадкового Професора.",
    tags: ["Пограбування", "Професор", "Токіо", "Червоні комбінезони", "Геній"],
    emojis: ["🧠", "😱", "🍿"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-lord-of-the-rings",
    title: "Володар перснів: Братство персня",
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring",
    year: 2001,
    genres: ["Фентезі", "Пригоди"],
    duration: 178,
    rating: 8.9,
    description: "Скромний хобіт із Ширу та вісім його супутників вирушають у небезпечну подорож до гори Фатум, щоб знищити могутній Єдиний Перстень і врятувати Середзем'я від темного володаря Саурона.",
    tags: ["Хобіти", "Гендальф", "Ельфи", "Середзем'я", "Епічна подорож", "Оскар"],
    emojis: ["🪄", "🤠", "🍿"],
    streaming: ["Megogo", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-fight-club",
    title: "Бійцівський клуб",
    originalTitle: "Fight Club",
    year: 1999,
    genres: ["Драма", "Трилер"],
    duration: 139,
    rating: 8.8,
    description: "Страждаючи від хронічного безсоння, звичайний офісний працівник створює підпільний бійцівський клуб разом із харизматичним і ексцентричним продавцем мила Тайлером Дерденом.",
    tags: ["Тайлер Дерден", "Роздвоєння особистості", "Анархія", "Бунт", "Несподіваний фінал"],
    emojis: ["🧠", "😱", "😭"],
    streaming: ["Netflix", "Apple TV", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-forrest-gump",
    title: "Форрест Гамп",
    originalTitle: "Forrest Gump",
    year: 1994,
    genres: ["Драма", "Романтика", "Комедія"],
    duration: 142,
    rating: 8.8,
    description: "Історія життя простого та неймовірно щирого хлопця з Алабами, який миволі стає свідком та безпосереднім учасником найважливіших історичних подій США середини ХХ століття.",
    tags: ["Том Генкс", "Життєва мудрість", "Коробка цукерок", "Біжи Форрест"],
    emojis: ["❤️", "😭", "😂"],
    streaming: ["Apple TV", "Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-sex-education",
    title: "Сексуальна освіта",
    originalTitle: "Sex Education",
    year: 2019,
    genres: ["Комедія", "Драма", "Серіал"],
    duration: 45,
    rating: 8.3,
    description: "Невпевнений підліток Отіс відкриває підпільну клініку секс-терапії для своїх однокласників, використовуючи знання, які мимовілі отримав від своєї мами — професійного сексолога.",
    tags: ["Школа", "Підлітки", "Дружба", "Гумор", "Сучасні проблеми"],
    emojis: ["😂", "❤️", "😭"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-pulp-fiction",
    title: "Кримінальне чтиво",
    originalTitle: "Pulp Fiction",
    year: 1994,
    genres: ["Трилер", "Комедія"],
    duration: 154,
    rating: 8.9,
    description: "Кілька взаємопов'язаних історій з життя дрібних злочинців, боксерів, гангстерів Джулса та Вінсента, а також таємничого пограбування кав'ярні у блискучому стилі Квентіна Тарантіно.",
    tags: ["Тарантіно", "Джон Траволта", "Культові діалоги", "Валіза", "Стильне"],
    emojis: ["🍿", "😂", "😱"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-ted-lasso",
    title: "Тед Лассо",
    originalTitle: "Ted Lasso",
    year: 2020,
    genres: ["Комедія", "Драма", "Серіал"],
    duration: 40,
    rating: 8.8,
    description: "Життєрадісний тренер з американського футболу Тед Лассо несподівано отримує запрошення очолити професійний футбольний клуб AFC Richmond в англійській Прем'єр-лізі, попри нульовий досвід у європейському футболі.",
    tags: ["Спорт", "Віра в себе", "Футбол", "Світла атмосфера", "Командний дух"],
    emojis: ["😂", "❤️", "🍿"],
    streaming: ["Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-squid-game",
    title: "Гра в кальмара",
    originalTitle: "Squid Game",
    year: 2021,
    genres: ["Трилер", "Драма", "Серіал"],
    duration: 55,
    rating: 8.0,
    description: "Сотні відчайдушних боржників погоджуються взяти участь у таємничій грі на виживання за гігантський грошовий приз, де дитячі ігри обертаються кривавою трагедією та жорстоким вибором.",
    tags: ["Виживання", "Корея", "Гроші", "Гра", "Гостросюжетний трилер"],
    emojis: ["😱", "😭", "🧠"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence", "tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1635805737707-575885ab0820?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-peaky-blinders",
    title: "Гострі картузи",
    originalTitle: "Peaky Blinders",
    year: 2013,
    genres: ["Драма", "Серіал"],
    duration: 58,
    rating: 8.8,
    description: "Епічна гангстерська сага про діяльність жорстокої циганської родини Шелбі у Бірмінгемі після Першої світової війни під керівництвом холодного та амбітного Томаса Шелбі.",
    tags: ["Томас Шелбі", "Кримінальна родина", "Бірмінгем", "Стильний візуал"],
    emojis: ["🍿", "🧠", "😭"],
    streaming: ["Netflix"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["violence"],
    posterUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-lion-king",
    title: "Король Лев",
    originalTitle: "The Lion King",
    year: 1994,
    genres: ["Анімація", "Пригоди", "Драма"],
    duration: 88,
    rating: 8.5,
    description: "Молоде левеня Сімба проходить через зраду свого підступного дядька Шрама, вигнання, дорослішання та знаходить вірних друзів Тимона й Пумбу, щоб згодом повернутись і відвоювати законний трон.",
    tags: ["Класика Disney", "Акуна Матата", "Музика", "Сімейний шедевр"],
    emojis: ["😭", "❤️", "🍿"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: ["animal-death", "tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "intl-truman-show",
    title: "Шоу Трумена",
    originalTitle: "The Truman Show",
    year: 1998,
    genres: ["Драма", "Комедія", "Наукова фантастика"],
    duration: 103,
    rating: 8.2,
    description: "Звичайний страховий агент Трумен Бербенк поступово починає розуміти, що все його життя є гігантським цілодобовим телешоу, де кожна людина — актор, а його містечко — декорація.",
    tags: ["Джим Керрі", "Реаліті-шоу", "Світ-декорація", "Свобода вибору", "Екзистенційне"],
    emojis: ["🧠", "😂", "😭"],
    streaming: ["Netflix", "Apple TV"],
    hasUkDub: true,
    isUkrainian: false,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-pobeda-berlin",
    title: "Я, Побєда і Берлін",
    originalTitle: "I, Pobeda and Berlin",
    year: 2024,
    genres: ["Комедія", "Пригоди"],
    duration: 104,
    rating: 8.0,
    description: "Божевільна та щира подорож молодого Кузьми Скрябіна до Німеччини на старій машині 'Побєда', яку він хоче обміняти на новенький Мерседес у місцевого німецького колекціонера. Неймовірна романтика 90-х.",
    tags: ["Кузьма Скрябін", "90-ті роки", "Музика", "Світлий гумор", "Дорожня пригода"],
    emojis: ["😂", "🤠", "❤️"],
    streaming: ["Sweet.tv", "Megogo"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: false,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-rhino",
    title: "Носоріг",
    originalTitle: "Rhino",
    year: 2021,
    genres: ["Драма", "Кримінал"],
    duration: 101,
    rating: 7.0,
    description: "Масштабне полотно про кримінальні 90-ті в Україні від режисера Олега Сенцова. Історія молодого агресивного хлопця на прізвисько Носоріг, який стрімко підіймається вершинами злочинного світу.",
    tags: ["90-ті роки", "Кримінал", "Олег Сенцов", "Сувора реальність"],
    emojis: ["😱", "😭", "🍿"],
    streaming: ["Netflix", "Sweet.tv"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: ["violence", "tragic-ending"],
    posterUrl: "https://images.unsplash.com/photo-1508615070457-7baeba4003ab?w=500&auto=format&fit=crop&q=80"
  },
  {
    id: "ua-volcano",
    title: "Вулкан",
    originalTitle: "Volcano",
    year: 2018,
    genres: ["Комедія", "Драма"],
    duration: 106,
    rating: 7.1,
    description: "Іронічний та містичний фільм Романа Бондарчука. Перекладач місії ОБСЄ застрягає в Богом забутому південноукраїнському містечку Берислав, де відкриває для себе цілком незнайомий світ анархії та абсурду.",
    tags: ["Херсонщина", "Абсурдний гумор", "Артхаус", "Колоритний степ"],
    emojis: ["😂", "🧠", "🪄"],
    streaming: ["Sweet.tv", "Netflix"],
    hasUkDub: true,
    isUkrainian: true,
    isHiddenGem: true,
    triggers: [],
    posterUrl: "https://images.unsplash.com/photo-1509803874385-db7c23652552?w=500&auto=format&fit=crop&q=80"
  }
];

export const INITIAL_CHALLENGES: MovieChallenge[] = [
  {
    id: "challenge-patriot",
    title: "Справжній Українець",
    description: "Подивись 3 дивовижних сучасних українських фільми.",
    badgeCode: "patriot",
    icon: "Heart",
    requirements: {
      count: 3,
      isUkrainian: true,
    },
    progress: 0,
    completed: false,
  },
  {
    id: "challenge-cineaste",
    title: "Кіноакадемік",
    description: "Оціни на свайпах або переглянь 5 гучних блокбастерів.",
    badgeCode: "cineaste",
    icon: "Award",
    requirements: {
      count: 5,
      genre: "Блокбастер", // Will map to blockbusters or highly rated in tags
    },
    progress: 0,
    completed: false,
  },
  {
    id: "challenge-goldhunter",
    title: "Шукач золотої руди",
    description: "Відкрий для себе 2 глибокі приховані перлини (Hidden Gems).",
    badgeCode: "goldhunter",
    icon: "Compass",
    requirements: {
      count: 2,
      isGem: true,
    },
    progress: 0,
    completed: false,
  },
];
